/* eslint-disable @typescript-eslint/no-unused-vars */
import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import { cn } from "@/lib/utils";
import {cookies} from "next/headers";

const roboto = Roboto({
   weight: ["100", "300", "500", "400", "700", "900"],
   style: ["normal", "italic"],
   subsets: ["latin"],
   display: "swap",
});
export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function Layout({
   root,
   auth,
}: {
   root: React.ReactNode;
   auth: React.ReactNode;
}) {
   const role = cookies().get('access_token')?.value;
   return (
      <html lang="en">
         <body className={cn("relative h-fit min-h-screen", roboto.className)}>
            {role ? root : auth}
         </body>
      </html>
   );
}
